version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: greenlight
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula

    ports:
      - 5555:8080